language: node_js
node_js:
  - 8

env:
  global:
    - GITHUB_REPO="github.com/WaiChungWong/waichungwong.github.io"

after_success: |
  if [ -n "$GITHUB_TOKEN" ]; then
    git checkout master
    npm run build
    rsync -r build/* .
    rm -rf build
    git add .
    git -c user.name="TravisCI" -c user.email="travis@travis-ci.org" commit -m "deploy website"
    git push -f -q "https://$GITHUB_TOKEN@${GITHUB_REPO}.git" master
  fi
